models/dep.py
from flask import render_template, Blueprint, url_for, redirect, request, flash
from sqlalchemy.exc import IntegrityError
from models.models import Employee, Department
from app.app import db
from forms.forrms  import DepartmentForm


dep = Blueprint("dep", __name__)


@dep.route("/departments")
def show_departments():
    """Render a list of all departments"""
    departments = Department.query.order_by(Department.id).all()
    employees = Employee.query.all()

    # Get information about all employees' salaries
    # and departments they belong to.
    salaries_info = {}
    for employee in employees:
        if employee.department_id in salaries_info:
            salaries_info[employee.department_id]["total"] += employee.salary
            salaries_info[employee.department_id]["count"] += 1
        else:
            salaries_info.update(
                {
                    employee.department_id: {
                        "total": employee.salary,
                        "count": 1,
                    }
                }
            )

    # Calculate average salaries for all departments
    # and store them in a dictionary.
    avg_salaries = {}
    for department in departments:
        if department.id in salaries_info:
            # If department has employees.
            avg_salaries[department.id] = (
                round(salaries_info[department.id]["total"]
                      / salaries_info[department.id]["count"], 2)
            )
        else:
            # Department has no employees.
            avg_salaries[department.id] = 0

    return render_template(
        "html/departaments.html", departments=departments,
        avg_salaries=avg_salaries, title="All departments"
    )


@dep.route("/add_department", methods=["GET", "POST"])
def add_department():
    """Add a new department using a form."""
    form = DepartmentForm()

    if form.validate_on_submit():
        # Set department name to a value from the form.
        department = Department(name=form.name.data)
        db.session.add(department)
        db.session.commit()
        flash("Department has been added!", "success")
        return redirect(url_for("dep.show_departments"))

    return render_template(
        "html/departament_add.html", title="Add new department",
        form=form, legend="New Department"
    )


@dep.route("/department/<int:department_id>")
def show_department(department_id):
    """Render page of a department with a given id"""
    department = Department.query.get_or_404(department_id)
    return render_template(
        "html/departament.html", title=department.name, department=department
    )


@dep.route("/department/<int:department_id>/update", methods=["GET", "POST"])
def update_department(department_id):
    """Delete department with a given id"""
    department = Department.query.get_or_404(department_id)
    form = DepartmentForm()

    if form.validate_on_submit():
        # Set department name to a value from the form.
        department.name = form.name.data
        db.session.commit()
        flash("Department has been updated!", "success")
        return redirect(url_for("dep.show_departments"))
    if request.method == "GET":
        # Fill the form with current value.
        form.name.data = department.name

    return render_template(
        "html/departament_add.html", title="Update department",
        form=form, legend=f"Update {department.name}"
    )


@dep.route("/department/<int:department_id>/delete", methods=["POST"])
def delete_department(department_id):
    """Delete department with a given id"""
    department = Department.query.get_or_404(department_id)
    try:
        db.session.delete(department)
        db.session.commit()
    except IntegrityError:
        # If department has employees handle an exception.
        flash("Department that has employees cannot be deleted!", "danger")
        return redirect(url_for("dep.show_departments"))
    else:
        # Redirect to departments page with success message.
        flash("Department has been deleted!", "success")
        return redirect(url_for("dep.show_departments"))

models/empl.py
from flask import render_template, Blueprint, url_for, redirect, request, flash
from models.models import Employee
from app.app import db
from forms.forrms import EmployeeForm, SearchForm
from datetime import datetime

emp = Blueprint("emp", __name__)


@emp.route("/employees")
def show_employees():
    """Render a list of all employees"""
    employees = Employee.query.order_by(Employee.id).all()
    return render_template("html/employees.html", employees=employees,
                           title="All employees")


@emp.route("/add_employee", methods=["GET", "POST"])
def add_employee():
    """Add a new employee using a form."""
    form = EmployeeForm()

    if form.validate_on_submit():
        # Create new Employee with values from the form.
        employee = Employee(
            salary=form.salary.data,
            name=form.name.data,
            date_of_birth=form.date_of_birth.data,
            department_id=form.department_id.data,
        )
        db.session.add(employee)
        db.session.commit()
        flash("Employee has been added!", "success")
        return redirect(url_for("emp.show_employees"))

    return render_template(
        "html/employee_add.html", title="Add new employee",
        form=form, legend="New Employee"
    )


@emp.route("/employee/<int:employee_id>")
def show_employee(employee_id):
    """Render page of an employee with a given id"""
    employee = Employee.query.get_or_404(employee_id)

    return render_template(
        "html/employee.html", title=employee.name, employee=employee
    )


@emp.route("/employee/<int:employee_id>/update", methods=["GET", "POST"])
def update_employee(employee_id):
    """Render page on which you can update information about an
    employee with a given id.
    """
    employee = Employee.query.get_or_404(employee_id)
    form = EmployeeForm()

    if form.validate_on_submit():
        # Set employee attributes to values from the form.
        employee.name = form.name.data
        employee.date_of_birth = form.date_of_birth.data
        employee.salary = form.salary.data
        employee.department_id = form.department_id.data
        db.session.commit()
        flash("Employee has been updated!", "success")
        return redirect(url_for("emp.show_employees"))
    if request.method == "GET":
        # Fill the form with current values.
        form.name.data = employee.name
        form.date_of_birth.data = employee.date_of_birth
        form.salary.data = employee.salary
        form.department_id.data = employee.department_id

    return render_template(
        "html/employee_add.html", title="Update employee",
        form=form, legend=f"Update {employee.name}"
    )


@emp.route("/employee/<int:employee_id>/delete", methods=["POST"])
def delete_employee(employee_id):
    """Delete employee with a given id"""

    employee = Employee.query.get_or_404(employee_id)
    db.session.delete(employee)
    db.session.commit()
    flash("Employee has been deleted!", "success")
    return redirect(url_for("emp.show_employees"))


@emp.route("/search_employees", methods=["GET", "POST"])
def search_employees():
    """Search employees by date of birth."""
    form = SearchForm()
    if form.validate_on_submit():
        employees = Employee.query\
            .filter(form.from_date.data <= Employee.date_of_birth,
                    Employee.date_of_birth <= form.to_date.data).all()
        return render_template("html/employees.html", employees=employees,
                               title="Search results")
    return render_template(
        "html/search.html", title="Search employees", form=form,
        legend="Search employees by date of birth"
    )

main.py
from flask import render_template, Blueprint


main = Blueprint("main", __name__)


@main.route("/")
def home():
    """Render home page"""
    return render_template("html/home.html", title="Home")

templates/html/departament.html
{% extends "index.html" %}
{% block content %}
  <div class="content-section">
    <h1>{{ department.name }}</h1>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">{{ department.id }}</th>
          <td>{{ department.name }}</td>
        </tr>
      </tbody>
    </table>
    <div>
      <a class="btn btn-secondary mt-1 mb-1" href="{{ url_for('dep.update_department', department_id=department.id) }}">Update</a>
      <button type="button" class="btn btn-danger m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Department?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('dep.delete_department', department_id=department.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/html/departament_add.html
{% extends "index.html" %}
{% block nav_right %}
  <a class="nav-item nav-link" href="{{ url_for('dep.show_departments') }}">Back to departments</a>
{% endblock %}
{% block content %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">{{ legend }}</legend>
        <div class="form-group">
          {{ form.name.label(class="form-control-label") }}
          {% if form.name.errors %}
            {{ form.name(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.name.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.name(class="form-control form-control-lg") }}
          {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
  </div>
{% endblock %}

templates/html/departaments.html
{% extends "index.html" %}
{% block nav_right %}
  <a class="nav-item nav-link" href="{{ url_for('dep.add_department') }}">New department</a>
{% endblock %}
{% block content %}
  <div class="content-section">
    <h1>Departments</h1>
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Average Salary</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for department in departments %}
          <tr>
            <td><a href="{{ url_for('dep.show_department', department_id=department.id) }}">{{ department.name }}</a></td>
            <td>{{ avg_salaries[department.id] }}</td>
            <td><a class="btn btn-secondary btn-sm" href="{{ url_for('dep.update_department', department_id=department.id) }}">Update</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/html/employee.html
{% extends "index.html" %}
{% block nav_right %}
  <a class="nav-item nav-link" href="{{ url_for('emp.search_employees') }}">Search employees</a>
  <a class="nav-item nav-link" href="{{ url_for('emp.add_employee') }}">New employee</a>
{% endblock %}
{% block content %}
  <div class="content-section">
    <h1>Employees</h1>
    {% if not employees %}
      <p>No results</p>
    {% else %}
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Date of Birth</th>
            <th scope="col">Salary</th>
            <th scope="col">Department</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for employee in employees %}
            <tr>
              <td><a href="{{ url_for('emp.show_employee', employee_id=employee.id) }}">{{ employee.name }}</a></td>
              <td>{{ employee.date_of_birth.strftime("%Y-%m-%d") }}</td>
              <td>{{ employee.salary }}</td>
              <td>{{ employee.department.name }}</td>
              <td><a class="btn btn-secondary btn-sm" href="{{ url_for('emp.update_employee', employee_id=employee.id) }}">Update</a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% endif %}
  </div>
{% endblock %}

templates/html/employee_add.html
{% extends "index.html" %}
{% block nav_right %}
  <a class="nav-item nav-link" href="{{ url_for('emp.show_employees') }}">Back to employees</a>
{% endblock %}
{% block content %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">{{ legend }}</legend>
        <div class="form-group">
          {{ form.name.label(class="form-control-label") }}
          {% if form.name.errors %}
            {{ form.name(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.name.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.name(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.date_of_birth.label(class="form-control-label") }}
          {% if form.date_of_birth.errors %}
            {{ form.date_of_birth(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.date_of_birth.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.date_of_birth(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.salary.label(class="form-control-label") }}
          {% if form.salary.errors %}
            {{ form.salary(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.salary.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.salary(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.department_id.label(class="form-control-label") }}
          {% if form.department_id.errors %}
            {{ form.department_id(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.department_id.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.department_id(class="form-control form-control-lg") }}
          {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
  </div>
{% endblock %}

templates/html/employees.html
{% extends "index.html" %}
{% block nav_right %}
  <a class="nav-item nav-link" href="{{ url_for('emp.search_employees') }}">Search employees</a>
  <a class="nav-item nav-link" href="{{ url_for('emp.add_employee') }}">New employee</a>
{% endblock %}
{% block content %}
  <div class="content-section">
    <h1>Employees</h1>
    {% if not employees %}
      <p>No results</p>
    {% else %}
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Date of Birth</th>
            <th scope="col">Salary</th>
            <th scope="col">Department</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for employee in employees %}
            <tr>
              <td><a href="{{ url_for('emp.show_employee', employee_id=employee.id) }}">{{ employee.name }}</a></td>
              <td>{{ employee.date_of_birth.strftime("%Y-%m-%d") }}</td>
              <td>{{ employee.salary }}</td>
              <td>{{ employee.department.name }}</td>
              <td><a class="btn btn-secondary btn-sm" href="{{ url_for('emp.update_employee', employee_id=employee.id) }}">Update</a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% endif %}
  </div>
{% endblock %}

templates/html/home.html
{% extends "layout.html" %}
{% block content %}
  <div class="content-section">
    <h1>Homepage</h1>
    <p>Welcome to our website for managing departments and employees!</p> 
    <p>Go to <a href="{{ url_for('dep.show_departments') }}">departments</a> if you
    want to see a list of all current departments or go to 
    <a href="{{ url_for('emp.show_employees') }}">employees</a> to see a list of
    all current employees.</p>
  </div>
{% endblock %}

templates/html/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>{{ title }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('dep.show_departments') }}">Departments</a>
              <a class="nav-item nav-link" href="{{ url_for('emp.show_employees') }}">Employees</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% block nav_right %}{% endblock %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div class="container">
        <div class="row">
          <div class="col-md-10 mx-auto">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}

            {% block content %}{% endblock %}
          </div>
        </div>
      </div>
    </main>

    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/html/search.html
{% extends "index.html" %}
{% block nav_right %}
  <a class="nav-item nav-link" href="{{ url_for('emp.show_employees') }}">Back to employees</a>
{% endblock %}
{% block content %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">{{ legend }}</legend>
        <div class="form-group">
          {{ form.from_date.label(class="form-control-label") }}
          {% if form.from_date.errors %}
            {{ form.from_date(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.from_date.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.from_date(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
            {{ form.to_date.label(class="form-control-label") }}
            {% if form.to_date.errors %}
              {{ form.to_date(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.to_date.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.to_date(class="form-control form-control-lg") }}
            {% endif %}
          </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
  </div>
{% endblock %}